package course.ee.demo.soap.boundary;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-06-06T07:24:07.666+02:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://boundary.soap.demo.ee.course/", name = "NoteService")
@XmlSeeAlso({ObjectFactory.class})
public interface NoteService {

    @WebMethod
    @RequestWrapper(localName = "getAll", targetNamespace = "http://boundary.soap.demo.ee.course/", className = "course.ee.demo.soap.boundary.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://boundary.soap.demo.ee.course/", className = "course.ee.demo.soap.boundary.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<course.ee.demo.soap.boundary.Note> getAll()
;
}
